vich_uploader:
    db_driver: orm

    mappings:
        peintures:
            uri_prefix: /uploads/peintures
            upload_destination: '%kernel.project_dir%/public/uploads/peintures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
